name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
jobs:
  release:
    name: Release to RubyGems
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb # v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - uses: rubygems/release-gem@a25424ba2ba8b387abc8ef40807c2c85b96cbe32 # v1
