name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  release:
    name: Release to RubyGems
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ruby/setup-ruby@50ba3386b050ad5b97a41fcb81240cbee1d1821f # v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - uses: rubygems/release-gem@612653d273a73bdae1df8453e090060bb4db5f31 # v1
