name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  release:
    name: Release to RubyGems
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb # v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - uses: rubygems/release-gem@612653d273a73bdae1df8453e090060bb4db5f31 # v1
